### ISSUE TITLE
Schriftgröße auf 12pt

### ISSUE THREAD

**Issue by CodingMarco** [Jo5ta/latex_template#2]
Nach den [Richtlinien](https://www.dhbw.de/fileadmin/user_upload/Dokumente/Dokumente_fuer_Studierende/191212_Leitlinien_Praxismodule_Studien_Bachelorarbeiten.pdf) sollte die Schriftgröße für alle Arbeiten 12pt sein.

Die Vorlage stellt nichts ein, somit wird der Latex-default von 10pt verwendet.
In der Main.tex sollte es `\documentclass[12pt, oneside, openbib, parskip = full-]{scrartcl}` heißen.

Oder gibt es einen bestimmten Grund für den Default von 10pt?

**Comment by Jo5ta** [comment]
Nein. Es gibt keine Grund. Ich ändere das.
